<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.832" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2025-01-15T09:50:27" tests="0" file="cypress\e2e\network\deleteRequests.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Requests: DELETE" timestamp="2025-01-15T09:50:27" tests="2" time="5.829" failures="1">
    <testcase name="Requests: DELETE should successfully complete deleting a player" time="0.000" classname="should successfully complete deleting a player">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul#players-list&gt;&apos; not to contain &apos;Player 2&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul#players-list>' not to contain 'Player 2'
    at Context.eval (webpack://players_crud1/./cypress/e2e/network/deleteRequests.cy.js:49:32)]]></failure>
    </testcase>
    <testcase name="Requests: DELETE should not delete a player if DELETE-request fails" time="0.757" classname="should not delete a player if DELETE-request fails">
    </testcase>
  </testsuite>
</testsuites>